name: Weekly Reminder

on:
  schedule:
    - cron: '0 14 * * 1'  # Every Monday at 9am EST, may be a few minutes lag due to git cron
  workflow_dispatch:  # Allows manual testing

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send to Google Chat
        run: |
          curl -X POST '${{ secrets.CHAT_WEBHOOK }}' -H 'Content-Type: application/json' -d '{"text": "ðŸ“… Weekly reminder: Update Office Poll!"}'
